# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: src/bag.proto for package 'bag'

require 'grpc'
require 'bag_pb'

module Bag
  module BagService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'bag.BagService'

      rpc :CreateApp, ::Bag::CreateAppRequest, ::Bag::CreateAppResponse
      rpc :CreateInstances, ::Bag::CreateInstancesRequest, ::Bag::CreateInstancesResponse
      rpc :CreateInstance, ::Bag::CreateInstanceRequest, ::Bag::CreateInstanceResponse
      rpc :CreateItem, ::Bag::CreateItemRequest, ::Bag::CreateItemResponse
      rpc :CreateRecipe, ::Bag::CreateRecipeRequest, ::Bag::CreateRecipeResponse
      rpc :CreateAction, ::Bag::CreateActionRequest, ::Bag::CreateActionResponse
      rpc :CreateTrade, ::Bag::CreateTradeRequest, ::Bag::CreateTradeResponse
      rpc :GetIdentities, ::Bag::GetIdentitiesRequest, ::Bag::GetIdentitiesResponse
      rpc :GetIdentity, ::Bag::GetIdentityRequest, ::Bag::GetIdentityResponse
      rpc :GetInventory, ::Bag::GetInventoryRequest, ::Bag::GetInventoryResponse
      rpc :GetItem, ::Bag::GetItemRequest, ::Bag::GetItemResponse
      rpc :GetItems, ::Bag::GetItemsRequest, ::Bag::GetItemsResponse
      rpc :GetInstance, ::Bag::GetInstanceRequest, ::Bag::GetInstanceResponse
      rpc :GetApp, ::Bag::GetAppRequest, ::Bag::GetAppResponse
      rpc :GetTrade, ::Bag::GetTradeRequest, ::Bag::GetTradeResponse
      rpc :GetRecipes, ::Bag::GetRecipesRequest, ::Bag::GetRecipesResponse
      rpc :GetRecipe, ::Bag::GetRecipeRequest, ::Bag::GetRecipeResponse
      rpc :GetAction, ::Bag::GetActionRequest, ::Bag::GetActionResponse
      rpc :UpdateIdentityMetadata, ::Bag::UpdateIdentityMetadataRequest, ::Bag::UpdateIdentityMetadataResponse
      rpc :UpdateInstance, ::Bag::UpdateInstanceRequest, ::Bag::UpdateInstanceResponse
      rpc :UpdateItem, ::Bag::UpdateItemRequest, ::Bag::UpdateItemResponse
      rpc :UpdateApp, ::Bag::UpdateAppRequest, ::Bag::UpdateAppResponse
      rpc :UpdateTrade, ::Bag::UpdateTradeRequest, ::Bag::UpdateTradeResponse
      rpc :UpdateRecipe, ::Bag::UpdateRecipeRequest, ::Bag::UpdateRecipeResponse
      rpc :UpdateAction, ::Bag::UpdateActionRequest, ::Bag::UpdateActionResponse
      rpc :DeleteApp, ::Bag::DeleteAppRequest, ::Bag::DeleteAppResponse
      rpc :DeleteInstance, ::Bag::DeleteInstanceRequest, ::Bag::DeleteInstanceResponse
      rpc :CloseTrade, ::Bag::CloseTradeRequest, ::Bag::CloseTradeResponse
      rpc :VerifyKey, ::Bag::VerifyKeyRequest, ::Bag::VerifyKeyResponse
      rpc :RunGive, ::Bag::RunGiveRequest, ::Bag::RunGiveResponse
      rpc :RunCraft, ::Bag::RunCraftRequest, ::Bag::RunCraftResponse
    end

    Stub = Service.rpc_stub_class
  end
end
